#! /bin/sh

set -e

case "$1" in
    configure)
	# not automatically created by dh_makeshlibs
        ldconfig
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
