#! /bin/sh

set -e

case "$1" in
	remove)
		# not automatically created by dh_makeshlibs
		ldconfig
	;;
	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

	*)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
